services:
  postgres:
    image: postgres:14.1
    container_name: outlinr_paas_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: outlinr_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - outlinr-network

  redis:
    image: redis:5.0.7
    container_name: outlinr_paas_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - outlinr-network

  buildkitd:
    image: moby/buildkit:latest
    container_name: outlinr_paas_buildkitd
    privileged: true
    ports:
      - "1234:1234"
    command: --addr tcp://0.0.0.0:1234
    volumes:
      - buildkitd_data:/var/lib/buildkit
    networks:
      - outlinr-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: outlinr_paas_api
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/outlinr_db
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
      - buildkitd
    volumes:
      - ./api/secrets:/app/secrets
    networks:
      - outlinr-network

  client:
    image: oven/bun:1.1-alpine
    container_name: outlinr_paas_client
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "bun install && bun run dev -- --host"
    environment:
      - VITE_API_URL=http://localhost:8080
      - VITE_GITHUB_APP_NAME=outlinr-dev
    depends_on:
      - api
    networks:
      - outlinr-network

volumes:
  pgdata:
  redisdata:
  buildkitd_data:

networks:
  outlinr-network:
    name: outlinr-network
