services:
  postgres:
    image: postgres:14.1
    container_name: outlinr_paas_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: outlinr_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - outlinr-network

  redis:
    image: redis:5.0.7
    container_name: outlinr_paas_redis
    volumes:
      - redisdata:/data
    networks:
      - outlinr-network

  buildkitd:
    image: moby/buildkit:latest
    container_name: outlinr_paas_buildkitd
    privileged: true
    command: --addr tcp://0.0.0.0:1234
    volumes:
      - buildkitd_data:/var/lib/buildkit
      - build_workspace:/tmp/builds
    networks:
      - outlinr-network

  caddy:
    image: caddy:latest
    container_name: outlinr_paas_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - outlinr-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: outlinr_paas_api
    env_file:
      - ./api/.env
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/outlinr_db
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
      - buildkitd
      - caddy
    volumes:
      - ./api/secrets:/app/secrets
      - build_workspace:/tmp/builds
      - images_workspace:/tmp/images
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - outlinr-network

volumes:
  pgdata:
  redisdata:
  buildkitd_data:
  caddy_data:
  caddy_config:
  build_workspace:
  images_workspace:

networks:
  outlinr-network:
    name: outlinr-network