server:
  forward-headers-strategy: FRAMEWORK

spring:
  application:
    name: api
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/api/login/oauth2/code/{registrationId}"
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

outlinr:
  domain: ${DOMAIN:localhost}
  client:
    url: ${CLIENT_URL}
  github:
    app-id: ${GITHUB_APP_ID}
    private-key-path: ${GITHUB_PRIVATE_KEY_PATH}
  buildkit:
    address: tcp://buildkitd:1234
  caddy:
    admin:
      url: ${CADDY_ADMIN_URL}
    upstream:
      host: ${CADDY_UPSTREAM_HOST}
